In [34]:
import pandas as pd
import numpy as np

In [35]:
cols = ['Player','Nation', 'Pos' ,'Age','MP','Starts','Min','90s','Gls',
        'Ast', 'G-PK','PK','PKatt','CrdY','CrdR','Per90Gls','Per90Ast','Per90G+A','Per90G-PK',
        'Per90G+A-PK','xG','npxG','xA','npxG+xAG','Per90xG','Per90xA','Per90xG+xA','Per90npxG','Per90npxG+xAG','Matches','-9999']

In [36]:
bk = pd.read_csv('datasets/Book1.csv',encoding = 'iso-8859-1')

In [37]:
bk.head()

  Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,xG,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999
0  Stuart Dallas,nir NIR,DFMF,29,38,38,3409,37.9,...
1  Luke Ayling,eng ENG,DF,28,38,38,3399,37.8,0,0,...
2  Patrick Bamford,eng ENG,FW,26,38,37,3050,33.9,...
3  Illan Meslier,fr FRA,GK,20,35,35,3150,35.0,0,0...
4  Jack Harrison,eng ENG,MF,23,36,34,2847,31.6,8,...

In [38]:
bk.shape

(23, 1)

In [39]:
bk.columns

Index(['Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,xG,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999'], dtype='object')

In [40]:
bk.rename(columns = {'Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,xG,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999': 'col'}, inplace = True)

In [41]:
#bk.col = bk.col.str.split(',')

In [42]:
df1 = pd.DataFrame(bk.col.str.split(',').tolist(),
                                 columns = cols)
df1

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,npxG,xA,npxG+xAG,Per90xG,Per90xA,Per90xG+xA,Per90npxG,Per90npxG+xAG,Matches,-9999
0,Stuart Dallas,nir NIR,DFMF,29,38,38,3409,37.9,8,2,...,4.6,2.1,6.7,0.12,0.05,0.18,0.12,0.18,Matches,67ca8566
1,Luke Ayling,eng ENG,DF,28,38,38,3399,37.8,0,0,...,1.4,2.6,4.0,0.04,0.07,0.10,0.04,0.10,Matches,420d7c7d
2,Patrick Bamford,eng ENG,FW,26,38,37,3050,33.9,17,7,...,15.7,4.1,19.8,0.51,0.12,0.63,0.46,0.59,Matches,93feac6e
3,Illan Meslier,fr FRA,GK,20,35,35,3150,35.0,0,0,...,0.0,0.1,0.1,0.00,0.00,0.00,0.00,0.00,Matches,6b625ac2
4,Jack Harrison,eng ENG,MF,23,36,34,2847,31.6,8,8,...,6.6,7.1,13.7,0.21,0.22,0.43,0.21,0.43,Matches,aa849a12
5,Ezgjan Alioski,mk MKD,DF,28,36,29,2461,27.3,2,3,...,1.5,3.1,4.6,0.05,0.11,0.17,0.05,0.17,Matches,1a7fcf39
6,Kalvin Phillips,eng ENG,MF,24,29,28,2428,27.0,1,2,...,0.4,3.8,4.1,0.01,0.14,0.15,0.01,0.15,Matches,4f565d77
7,Mateusz Klich,pl POL,MF,30,35,28,2393,26.6,4,5,...,1.8,3.9,5.7,0.13,0.15,0.27,0.07,0.22,Matches,282679b4
8,Raphinha,br BRA,MF,23,30,26,2360,26.2,6,9,...,6.0,8.1,14.1,0.23,0.31,0.54,0.23,0.54,Matches,3423f250
9,Liam Cooper,sct SCO,DF,28,25,25,2185,24.3,1,0,...,1.3,0.0,1.3,0.05,0.00,0.05,0.05,0.05,Matches,dc64b8b3
10,Pascal Struijk,nl NED,DFMF,20,27,22,2075,23.1,1,0,...,2.4,0.2,2.6,0.10,0.01,0.11,0.10,0.11,Matches,f4d296e4
11,Tyler Roberts,wls WAL,MFFW,21,27,14,1340,14.9,1,2,...,2.1,1.8,3.8,0.14,0.12,0.26,0.14,0.26,Matches,6c17e046
12,Rodrigo,es ESP,MFFW,29,26,14,1288,14.3,7,2,...,6.3,2.4,8.6,0.44,0.17,0.60,0.44,0.60,Matches,1fb1c435
13,Diego Llorente,es ESP,DF,26,15,14,1204,13.4,1,0,...,0.7,0.6,1.4,0.06,0.05,0.10,0.06,0.10,Matches,bba30585
14,Hélder Costa,ao ANG,MFFW,26,22,13,1156,12.8,3,3,...,2.0,0.9,2.9,0.16,0.07,0.23,0.16,0.23,Matches,f13d02a6
15,Robin Koch,de GER,DFMF,24,17,13,1132,12.6,0,0,...,0.8,0.2,1.0,0.06,0.01,0.08,0.06,0.08,Matches,ea6bc03a
16,Jamie Shackleton,eng ENG,MFDF,20,13,3,461,5.1,0,0,...,0.0,0.3,0.3,0.00,0.05,0.05,0.00,0.05,Matches,8d03ca5a
17,Pablo Hernández,es ESP,MFFW,35,16,3,427,4.7,0,2,...,1.2,0.7,1.8,0.25,0.14,0.39,0.25,0.39,Matches,c0398aca
18,Kiko Casilla,es ESP,GK,33,3,3,270,3.0,0,0,...,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches,58bc7d18
19,Gaetano Berardi,ch SUI,DF,31,2,1,113,1.3,0,0,...,0.0,0.0,0.0,0.03,0.00,0.03,0.03,0.03,Matches,5348aada
20,Ian Carlo Poveda,eng ENG,MFDF,20,14,0,355,3.9,0,0,...,0.4,0.8,1.2,0.09,0.21,0.30,0.09,0.30,Matches,55b4f1d6
21,Niall Huggins,wls WAL,DF,19,1,0,38,0.4,0,0,...,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches,6d646ff7
22,Leif Davis,eng ENG,DF,20,2,0,33,0.4,0,0,...,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,Matches,8574c61f

In [43]:
df1.drop(columns = ['Matches', '-9999'], inplace = True)

In [44]:
df1.shape

(23, 29)

In [45]:
df1.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Per90G+A-PK,xG,npxG,xA,npxG+xAG,Per90xG,Per90xA,Per90xG+xA,Per90npxG,Per90npxG+xAG
0,Stuart Dallas,nir NIR,DFMF,29,38,38,3409,37.9,8,2,...,0.26,4.6,4.6,2.1,6.7,0.12,0.05,0.18,0.12,0.18
1,Luke Ayling,eng ENG,DF,28,38,38,3399,37.8,0,0,...,0.00,1.4,1.4,2.6,4.0,0.04,0.07,0.10,0.04,0.10
2,Patrick Bamford,eng ENG,FW,26,38,37,3050,33.9,17,7,...,0.65,17.3,15.7,4.1,19.8,0.51,0.12,0.63,0.46,0.59
3,Illan Meslier,fr FRA,GK,20,35,35,3150,35.0,0,0,...,0.00,0.0,0.0,0.1,0.1,0.00,0.00,0.00,0.00,0.00
4,Jack Harrison,eng ENG,MF,23,36,34,2847,31.6,8,8,...,0.51,6.6,6.6,7.1,13.7,0.21,0.22,0.43,0.21,0.43

Leeds Season 2021/22 (2nd Season)

In [46]:
bk1 = pd.read_csv('datasets/leeds-2021-22.csv',encoding = 'iso-8859-1')

In [47]:
bk1.rename(columns = {'Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK,xG,npxG,xA,npxG+xA,xG,xA,xG+xA,npxG,npxG+xA,Matches,-9999': 'col'}, inplace = True)

In [48]:
df2 = pd.DataFrame(bk1.col.str.split(',').tolist(),
                                 columns = cols)
df2.drop(columns = ['Matches', '-9999'], inplace = True)

In [49]:
df2.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,...,Per90G+A-PK,xG,npxG,xA,npxG+xAG,Per90xG,Per90xA,Per90xG+xA,Per90npxG,Per90npxG+xAG
0,Illan Meslier,fr FRA,GK,21,38,38,3384,37.6,0,0,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Stuart Dallas,nir NIR,DFMF,30,34,34,2919,32.4,1,1,...,0.06,2.0,2.0,2.1,4.0,0.06,0.06,0.12,0.06,0.12
2,Raphinha,br BRA,FWMF,24,35,34,2915,32.4,11,3,...,0.31,11.3,8.2,6.8,15.0,0.35,0.21,0.56,0.25,0.46
3,Jack Harrison,eng ENG,FWMF,24,35,32,2639,29.3,8,1,...,0.31,4.0,4.0,2.6,6.6,0.14,0.09,0.23,0.14,0.23
4,Daniel James,wls WAL,FWMF,23,32,29,2366,26.3,4,4,...,0.30,5.4,5.4,2.4,7.9,0.21,0.09,0.30,0.21,0.30

In [50]:
datafiles = ['datasets/brighton2017-2018.csv', 'datasets/brighton2018-2019.csv', 'datasets/hudds2017-2018.csv',
            'datasets/hudds2018-2019.csv', 'datasets/newcastle2017-2018.csv', 'datasets/newcastle2018-2019.csv',
            'datasets/sheffutd2019-2020.csv', 'datasets/sheffutd2020-2021.csv', 'datasets/villa2019-2020.csv',
            'datasets/villa2020-2021.csv', 'datasets/wolves-18-19-attack.csv', 'datasets/wolves-19-20-attack.csv']

dfnames = ['df3', 'df4', 'df5', 'df6', 'df7', 'df8', 'df9', 'df10', 'df11', 'df12', 'df13', 'df14']

In [51]:
for i in range(len(datafiles)):
    csvfile = pd.read_csv(datafiles[i], encoding = 'iso-8859-1')
    lsttt = list(csvfile.columns)
    #print(lsttt)
    #print(csvfile.columns)
    dfnames[i] = pd.DataFrame(csvfile.iloc[:, 0].str.split(',').tolist(),
                                 columns = cols)
    if 'ï»¿"Player' in csvfile.columns:
        csvfile = csvfile.rename(columns = {'ï»¿"Player': 'Name'})
    else:
        csvfile = csvfile.rename(columns = {'Player': 'Name'})
    dfnames[i].drop(columns = ['Matches', '-9999'], inplace = True)

In [52]:
df3 = dfnames[0]
df4 = dfnames[1]
df5 = dfnames[2]
df6 = dfnames[3]
df7 = dfnames[4]
df8 = dfnames[5]
df9 = dfnames[6]
df10 = dfnames[7]
df11 = dfnames[8]
df12 = dfnames[9]
df13 = dfnames[10]
df14 = dfnames[11]

In [53]:
#df1.to_csv("datasets\cleanedbasic\leeds20-21.csv", index=False)
#df2.to_csv("datasets\cleanedbasic\leeds21-22.csv", index=False)

In [54]:
#df9.to_csv("datasets\cleanedbasic\sheffutd19-20.csv", index=False)
#df10.to_csv("datasets\cleanedbasic\sheffutd20-21.csv", index=False)

In [55]:
#df5.to_csv("datasets\cleanedbasic\hudds17-18.csv", index=False)
#df6.to_csv("datasets\cleanedbasic\hudds18-19.csv", index=False)

In [56]:
df3.to_csv("datasets/cleanedbasic/brighton17-18.csv", index=False)
df4.to_csv("datasets/cleanedbasic/brighton18-19.csv", index=False)